<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="590" started-at="2020-06-04T08:21:02Z" finished-at="2020-06-04T08:21:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="590" started-at="2020-06-04T08:21:02Z" finished-at="2020-06-04T08:21:02Z">
      <class name="com.infoglenretest.tests.TestSuite">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.infoglenretest.tests.TestSuite@56ef9176]" name="beforeTest" is-config="true" duration-ms="13" started-at="2020-06-04T16:21:02Z" finished-at="2020-06-04T16:21:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:com.infoglenretest.tests.TestSuite@56ef9176]" name="launchBrowser" is-config="true" duration-ms="0" started-at="2020-06-04T16:21:02Z" finished-at="2020-06-04T16:21:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="postResponseShouldBe201()[pri:3, instance:com.infoglenretest.tests.TestSuite@56ef9176]" name="postResponseShouldBe201" duration-ms="546" started-at="2020-06-04T16:21:02Z" finished-at="2020-06-04T16:21:02Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.infoglenretest.tests.TestSuite.postResponseShouldBe201(TestSuite.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postResponseShouldBe201 -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:com.infoglenretest.tests.TestSuite@56ef9176]" name="closeDriver" is-config="true" duration-ms="1" started-at="2020-06-04T16:21:02Z" finished-at="2020-06-04T16:21:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- com.infoglenretest.tests.TestSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
